// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package backend

import (
	"context"
	"github.com/kuno989/friday/backend/pkg"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func InitializeServer(ctx context.Context, cfg *viper.Viper) (*Server, func(), error) {
	serverConfig, err := ProvideServerConfig(cfg)
	if err != nil {
		return nil, nil, err
	}
	mongoConfig, err := pkg.ProvideMongoConfig(cfg)
	if err != nil {
		return nil, nil, err
	}
	mongo, cleanup, err := pkg.NewMongo(ctx, mongoConfig)
	if err != nil {
		return nil, nil, err
	}
	rabbitMqConfig, err := pkg.ProvideRabbitMqConfig(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	rabbitMq, cleanup2, err := pkg.NewRabbitMq(rabbitMqConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	server := NewServer(serverConfig, mongo, rabbitMq)
	return server, func() {
		cleanup2()
		cleanup()
	}, nil
}
