// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package drweb_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DrWebScannerClient is the client API for DrWebScanner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DrWebScannerClient interface {
	ScanFile(ctx context.Context, in *ScanFileRequest, opts ...grpc.CallOption) (*ScanResponse, error)
	GetVersion(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
}

type drWebScannerClient struct {
	cc grpc.ClientConnInterface
}

func NewDrWebScannerClient(cc grpc.ClientConnInterface) DrWebScannerClient {
	return &drWebScannerClient{cc}
}

func (c *drWebScannerClient) ScanFile(ctx context.Context, in *ScanFileRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, "/drweb.DrWebScanner/ScanFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drWebScannerClient) GetVersion(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/drweb.DrWebScanner/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DrWebScannerServer is the server API for DrWebScanner service.
// All implementations must embed UnimplementedDrWebScannerServer
// for forward compatibility
type DrWebScannerServer interface {
	ScanFile(context.Context, *ScanFileRequest) (*ScanResponse, error)
	GetVersion(context.Context, *VersionRequest) (*VersionResponse, error)
	mustEmbedUnimplementedDrWebScannerServer()
}

// UnimplementedDrWebScannerServer must be embedded to have forward compatible implementations.
type UnimplementedDrWebScannerServer struct {
}

func (UnimplementedDrWebScannerServer) ScanFile(context.Context, *ScanFileRequest) (*ScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScanFile not implemented")
}
func (UnimplementedDrWebScannerServer) GetVersion(context.Context, *VersionRequest) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedDrWebScannerServer) mustEmbedUnimplementedDrWebScannerServer() {}

// UnsafeDrWebScannerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DrWebScannerServer will
// result in compilation errors.
type UnsafeDrWebScannerServer interface {
	mustEmbedUnimplementedDrWebScannerServer()
}

func RegisterDrWebScannerServer(s grpc.ServiceRegistrar, srv DrWebScannerServer) {
	s.RegisterService(&DrWebScanner_ServiceDesc, srv)
}

func _DrWebScanner_ScanFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrWebScannerServer).ScanFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drweb.DrWebScanner/ScanFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrWebScannerServer).ScanFile(ctx, req.(*ScanFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DrWebScanner_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrWebScannerServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/drweb.DrWebScanner/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrWebScannerServer).GetVersion(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DrWebScanner_ServiceDesc is the grpc.ServiceDesc for DrWebScanner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DrWebScanner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "drweb.DrWebScanner",
	HandlerType: (*DrWebScannerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScanFile",
			Handler:    _DrWebScanner_ScanFile_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _DrWebScanner_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "drweb.proto",
}
