// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package comodo_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ComodoScannerClient is the client API for ComodoScanner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ComodoScannerClient interface {
	ScanFile(ctx context.Context, in *ScanFileRequest, opts ...grpc.CallOption) (*ScanResponse, error)
	GetVersion(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
}

type comodoScannerClient struct {
	cc grpc.ClientConnInterface
}

func NewComodoScannerClient(cc grpc.ClientConnInterface) ComodoScannerClient {
	return &comodoScannerClient{cc}
}

func (c *comodoScannerClient) ScanFile(ctx context.Context, in *ScanFileRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, "/comodo.ComodoScanner/ScanFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *comodoScannerClient) GetVersion(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/comodo.ComodoScanner/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComodoScannerServer is the server API for ComodoScanner service.
// All implementations must embed UnimplementedComodoScannerServer
// for forward compatibility
type ComodoScannerServer interface {
	ScanFile(context.Context, *ScanFileRequest) (*ScanResponse, error)
	GetVersion(context.Context, *VersionRequest) (*VersionResponse, error)
	mustEmbedUnimplementedComodoScannerServer()
}

// UnimplementedComodoScannerServer must be embedded to have forward compatible implementations.
type UnimplementedComodoScannerServer struct {
}

func (UnimplementedComodoScannerServer) ScanFile(context.Context, *ScanFileRequest) (*ScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScanFile not implemented")
}
func (UnimplementedComodoScannerServer) GetVersion(context.Context, *VersionRequest) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedComodoScannerServer) mustEmbedUnimplementedComodoScannerServer() {}

// UnsafeComodoScannerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComodoScannerServer will
// result in compilation errors.
type UnsafeComodoScannerServer interface {
	mustEmbedUnimplementedComodoScannerServer()
}

func RegisterComodoScannerServer(s grpc.ServiceRegistrar, srv ComodoScannerServer) {
	s.RegisterService(&ComodoScanner_ServiceDesc, srv)
}

func _ComodoScanner_ScanFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComodoScannerServer).ScanFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comodo.ComodoScanner/ScanFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComodoScannerServer).ScanFile(ctx, req.(*ScanFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComodoScanner_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComodoScannerServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/comodo.ComodoScanner/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComodoScannerServer).GetVersion(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ComodoScanner_ServiceDesc is the grpc.ServiceDesc for ComodoScanner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ComodoScanner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "comodo.ComodoScanner",
	HandlerType: (*ComodoScannerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScanFile",
			Handler:    _ComodoScanner_ScanFile_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _ComodoScanner_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comodo.proto",
}
